# Generated by Django 3.1.3 on 2020-11-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
